context("Test http error class")

test_that("test empty object", {
  e = HTTPErrorFactory$new()
  expect_is(e, "HTTPErrorFactory")
  expect_null(e$body)
  expect_null(e$headers)
  expect_null(e$status_code)
  expect_is(e$content_type, "character")
  expect_length(e$content_type, 1L)
  expect_equal(e$content_type, "text/plain")
  expect_is(e$serializer, "function")
  expect_equal(e$serializer, as.character)
})


test_that("test not found", {
  e = HTTPErrorFactory$new()$not_found()
  expect_is(e$body, "character")
  expect_length(e$body, 1L)
  expect_equal(e$body, "404 Not Found")
  expect_is(e$content_type, "character")
  expect_length(e$content_type, 1L)
  expect_equal(e$content_type, "text/plain")
  expect_is(e$status_code, "integer")
  expect_length(e$status_code, 1L)
  expect_equal(e$status_code, 404L)
  expect_is(e$serializer, "function")
  expect_equal(e$serializer, as.character)
})
