context("Test http error class")

obj = HTTPErrorFactory$new()

test_that("Test empty object", {
  expect_is(obj, "HTTPErrorFactory")
  expect_null(obj$body)
  expect_null(obj$headers)
  expect_null(obj$status_code)
  expect_is(obj$content_type, "character")
  expect_length(obj$content_type, 1L)
  expect_equal(obj$content_type, "text/plain")
  expect_is(obj$serializer, "function")
  expect_equal(obj$serializer, as.character)
})

test_that("Test not_found", {
  resp = obj$not_found()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "404 Not Found")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 404L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})

test_that("Test bad_request", {
  resp = obj$bad_request()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "400 Bad Request")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 400L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})

test_that("Test unauthorized", {
  resp = obj$unauthorized()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "401 Unauthorized")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 401L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})

test_that("Test forbidden", {
  resp = obj$forbidden()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "403 Forbidden")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 403L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})

test_that("Test internal_server_error", {
  resp = obj$internal_server_error()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "500 Internal Server Error")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 500L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})

test_that("Test not_implemented", {
  resp = obj$not_implemented()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "501 Not Implemented")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 501L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})

test_that("Test bad_gateway", {
  resp = obj$bad_gateway()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "502 Bad Gateway")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 502L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})

test_that("Test service_unavailable", {
  resp = obj$service_unavailable()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "503 Service Unavailable")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 503L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})

test_that("Test gateway_timeout", {
  resp = obj$gateway_timeout()
  expect_is(resp, "RestRserveResponse")
  expect_is(resp$body, "character")
  expect_length(resp$body, 1L)
  expect_equal(resp$body, "504 Gateway Timeout")
  expect_is(resp$content_type, "character")
  expect_length(resp$content_type, 1L)
  expect_equal(resp$content_type, "text/plain")
  expect_is(resp$status_code, "integer")
  expect_length(resp$status_code, 1L)
  expect_equal(resp$status_code, 504L)
  expect_is(resp$serializer, "function")
  expect_equal(resp$serializer, as.character)
})
