// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_format_cookies
Rcpp::CharacterVector cpp_format_cookies(Rcpp::ListOf<Rcpp::List> cookies);
RcppExport SEXP _RestRserve_cpp_format_cookies(SEXP cookiesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::ListOf<Rcpp::List> >::type cookies(cookiesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_format_cookies(cookies));
    return rcpp_result_gen;
END_RCPP
}
// cpp_format_headers
Rcpp::CharacterVector cpp_format_headers(Rcpp::ListOf<Rcpp::CharacterVector> x);
RcppExport SEXP _RestRserve_cpp_format_headers(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::ListOf<Rcpp::CharacterVector> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_format_headers(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_parse_cookies
Rcpp::List cpp_parse_cookies(Rcpp::CharacterVector x);
RcppExport SEXP _RestRserve_cpp_parse_cookies(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_parse_cookies(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_parse_headers
Rcpp::List cpp_parse_headers(const char* headers, Rcpp::Nullable<const Rcpp::CharacterVector> headers_to_split);
RcppExport SEXP _RestRserve_cpp_parse_headers(SEXP headersSEXP, SEXP headers_to_splitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const char* >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<const Rcpp::CharacterVector> >::type headers_to_split(headers_to_splitSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_parse_headers(headers, headers_to_split));
    return rcpp_result_gen;
END_RCPP
}
// cpp_parse_multipart_boundary
std::string cpp_parse_multipart_boundary(const std::string& content_type);
RcppExport SEXP _RestRserve_cpp_parse_multipart_boundary(SEXP content_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::string& >::type content_type(content_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_parse_multipart_boundary(content_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_parse_multipart_body
Rcpp::List cpp_parse_multipart_body(Rcpp::RawVector body, const char* boundary);
RcppExport SEXP _RestRserve_cpp_parse_multipart_body(SEXP bodySEXP, SEXP boundarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type body(bodySEXP);
    Rcpp::traits::input_parameter< const char* >::type boundary(boundarySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_parse_multipart_body(body, boundary));
    return rcpp_result_gen;
END_RCPP
}
// raw_slice
Rcpp::RawVector raw_slice(const Rcpp::RawVector& x, const R_xlen_t offset, const R_xlen_t size);
RcppExport SEXP _RestRserve_raw_slice(SEXP xSEXP, SEXP offsetSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const R_xlen_t >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const R_xlen_t >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(raw_slice(x, offset, size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_url_decode
Rcpp::CharacterVector cpp_url_decode(Rcpp::CharacterVector x);
RcppExport SEXP _RestRserve_cpp_url_decode(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_url_decode(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_url_encode
Rcpp::CharacterVector cpp_url_encode(Rcpp::CharacterVector x);
RcppExport SEXP _RestRserve_cpp_url_encode(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_url_encode(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RestRserve_cpp_format_cookies", (DL_FUNC) &_RestRserve_cpp_format_cookies, 1},
    {"_RestRserve_cpp_format_headers", (DL_FUNC) &_RestRserve_cpp_format_headers, 1},
    {"_RestRserve_cpp_parse_cookies", (DL_FUNC) &_RestRserve_cpp_parse_cookies, 1},
    {"_RestRserve_cpp_parse_headers", (DL_FUNC) &_RestRserve_cpp_parse_headers, 2},
    {"_RestRserve_cpp_parse_multipart_boundary", (DL_FUNC) &_RestRserve_cpp_parse_multipart_boundary, 1},
    {"_RestRserve_cpp_parse_multipart_body", (DL_FUNC) &_RestRserve_cpp_parse_multipart_body, 2},
    {"_RestRserve_raw_slice", (DL_FUNC) &_RestRserve_raw_slice, 3},
    {"_RestRserve_cpp_url_decode", (DL_FUNC) &_RestRserve_cpp_url_decode, 1},
    {"_RestRserve_cpp_url_encode", (DL_FUNC) &_RestRserve_cpp_url_encode, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RestRserve(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
