# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_format_cookies <- function(cookies) {
    .Call(`_RestRserve_cpp_format_cookies`, cookies)
}

cpp_format_headers <- function(x) {
    .Call(`_RestRserve_cpp_format_headers`, x)
}

cpp_parse_cookies <- function(x) {
    .Call(`_RestRserve_cpp_parse_cookies`, x)
}

cpp_parse_headers <- function(headers, headers_to_split = NULL) {
    .Call(`_RestRserve_cpp_parse_headers`, headers, headers_to_split)
}

cpp_parse_multipart_boundary <- function(content_type) {
    .Call(`_RestRserve_cpp_parse_multipart_boundary`, content_type)
}

cpp_parse_multipart_body <- function(body, boundary) {
    .Call(`_RestRserve_cpp_parse_multipart_body`, body, boundary)
}

raw_slice <- function(x, offset, size) {
    .Call(`_RestRserve_raw_slice`, x, offset, size)
}

cpp_url_decode <- function(x) {
    .Call(`_RestRserve_cpp_url_decode`, x)
}

cpp_url_encode <- function(x) {
    .Call(`_RestRserve_cpp_url_encode`, x)
}

