# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_format_cookies <- function(cookies) {
    .Call(`_RestRserve_cpp_format_cookies`, cookies)
}

cpp_format_headers <- function(x) {
    .Call(`_RestRserve_cpp_format_headers`, x)
}

cpp_parse_cookies <- function(x) {
    .Call(`_RestRserve_cpp_parse_cookies`, x)
}

#' Returns a vector of http header names which are split by default
#'
#' @return A vector of http header names
#' @export
#'
#' @seealso [https://en.wikipedia.org/wiki/List_of_HTTP_header_fields]() and
#' [https://stackoverflow.com/a/29550711/3048453]()
http_headers_to_split_default <- function() {
    .Call(`_RestRserve_http_headers_to_split_default`)
}

cpp_parse_headers <- function(headers, headers_to_split = NULL) {
    .Call(`_RestRserve_cpp_parse_headers`, headers, headers_to_split)
}

cpp_parse_multipart_boundary <- function(content_type) {
    .Call(`_RestRserve_cpp_parse_multipart_boundary`, content_type)
}

cpp_parse_multipart_body <- function(body, boundary) {
    .Call(`_RestRserve_cpp_parse_multipart_body`, body, boundary)
}

raw_slice <- function(x, offset, size) {
    .Call(`_RestRserve_raw_slice`, x, offset, size)
}

cpp_url_decode <- function(x) {
    .Call(`_RestRserve_cpp_url_decode`, x)
}

cpp_url_encode <- function(x) {
    .Call(`_RestRserve_cpp_url_encode`, x)
}

