name: Build tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Docker
      run: curl https://get.docker.com | sh

    - name: Set tag name
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:$(echo $TAG | tr -dc '0-9\.') -f docker/Dockerfile .

    - name: Push image
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} && docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:$(echo $TAG | tr -dc '0-9\.')

    - name: Build minimal image
      run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:$(echo $TAG | tr -dc '0-9\.')-minimal -f docker/Dockerfile-r-minimal .

    - name: Push minimal image
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} && docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:$(echo $TAG | tr -dc '0-9\.')-minimal
