name: Build tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Docker
      run: curl https://get.docker.com | sh

    - name: Set tag name
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo "DOCKER_IMAGE=rexyai/restrserve:$(echo $TAG | tr -dc '0-9\.')" >> $GITHUB_ENV

    - name: Build standard image
      run: docker build -t ${DOCKER_IMAGE} -f docker/Dockerfile .

    - name: Build alpine image
      run: docker build -t ${DOCKER_IMAGE}-alpine -f docker/Dockerfile-r-minimal .

    - name: Push images
      run: docker login -u dselivanov -p ${{ secrets.DOCKER_TOKEN }} && \
        docker push ${DOCKER_IMAGE} && \
        docker push ${DOCKER_IMAGE}-alpine
